name: Deploy MultiK8s
on:
  push:
    branches: [ "master" ]
  

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ifedim/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true ifedim/react-test npm test

      - name: Set Service Key
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: kubernetes-gitaction 

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: cluster-1
          location: us-central1-a 

      - name: Build
        run: |-
          docker build -t ifedim/multi-client:latest -t ifedim/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t ifedim/multi-server:latest -t ifedim/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t ifedim/multi-worker:latest -t ifedim/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push ifedim/multi-client:latest
          docker push ifedim/multi-server:latest
          docker push ifedim/multi-worker:latest

          docker push ifedim/multi-client:${{ env.SHA }}
          docker push ifedim/multi-server:${{ env.SHA }}
          docker push ifedim/multi-worker:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f "k8's"
          kubectl set image deployments/server-deployment server=ifedim/multi-server:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=ifedim/multi-client:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=ifedim/multi-worker:${{ env.SHA }}
